In [2]:
import pandas as pd

In [20]:
df1= pd.read_parquet('Predictors/sm-calls_summarized_post2018.parquet', engine='fastparquet')
df1.head()

,transcriptid,permno,mostimportantdateutc,mostimportanttimeutc,audiolengthsec,text,text_length,word_count,companyid,companyname,headline,ec_summary
0,1665720.0,80191.0,2019-02-21,50400000000,3844.0,"Good day, ladies and gentlemen, and welcome to...",51197,8924,18671.0,Albemarle Corporation,"Albemarle Corporation, Q4 2018 Earnings Call, ...",Albemarle Corporation reported robust Q4 2018 ...
1,1927283.0,80191.0,2020-02-20,50400000000,3453.0,"Ladies and gentlemen, thank you for standing b...",46756,7999,18671.0,Albemarle Corporation,"Albemarle Corporation, Q4 2019 Earnings Call, ...",Albemarle Corp. reported Q4 2019 revenues and ...
2,2215483.0,80191.0,2021-02-18,50400000000,3674.0,"Ladies and gentlemen, thank you for standing b...",52160,9070,18671.0,Albemarle Corporation,"Albemarle Corporation, Q4 2020 Earnings Call, ...",Albemarle reported Q4 2020 revenues of $879M a...
3,2740261.0,80191.0,2023-02-16,50400000000,1833.0,"Ladies and gentlemen, welcome to the Albemarle...",25591,4475,18671.0,Albemarle Corporation,"Albemarle Corporation, Q4 2022 Earnings Call, ...",Albemarle Corporation reported exceptional Q4 ...
4,1651047.0,79323.0,2019-02-06,52200000000,3831.0,"Good day, ladies and gentlemen, and welcome to...",55770,9728,18711.0,The Allstate Corporation,"The Allstate Corporation, Q4 2018 Earnings Cal...",Allstate reported Q4 2018 revenues of $10.4B a...

In [23]:
df2= pd.read_parquet('merged_data.parquet', engine='fastparquet')
df2.head()

,date,text,industry,ret_3M_shifted
0,2020-11,J&J Snack Foods reported Q4 2022 revenues down...,Food & Beverage Manufacturing,-0.007357
1,2021-11,J&J Snack Foods reported strong Q4 2021 result...,Food & Beverage Manufacturing,-0.048821
2,2023-11,J&J Snack Foods reported robust Q4 2023 and FY...,Food & Beverage Manufacturing,0.001644
3,2021-10,Plexus reported Q4 2021 GAAP EPS of $1.16 and ...,Electronic & Electrical Equipment,0.050955
4,2022-10,Plexus Corp. reported Q4 2022 revenue of $1.12...,Electronic & Electrical Equipment,-0.001042

In [24]:
df3 = pd.read_parquet('Predictors/sm-calls_with_connectors.parquet', engine='fastparquet')
df3.head()

,transcriptid,permno,mostimportantdateutc,mostimportanttimeutc,audiolengthsec,text,text_length,word_count,companyid,companyname,headline
0,18033.0,80191.0,2008-01-29,0 days 14:00:00,NaN,"Good day, ladies and gentlemen, and welcome to...",63457,10905,18671.0,Albemarle Corporation,"Albemarle Corp., Q4 2007 Earnings Call, Jan-29..."
1,15710.0,80191.0,2009-01-27,0 days 15:00:00,NaN,"Good day ladies and gentlemen, and welcome to ...",53141,9252,18671.0,Albemarle Corporation,"Albemarle Corp., Q4 2008 Earnings Call, Jan-27..."
2,46982.0,80191.0,2010-01-26,0 days 15:00:00,4740.0,"Good day, ladies and gentlemen, and welcome to...",66535,11616,18671.0,Albemarle Corporation,"Albemarle Corp., Q4 2009 Earnings Call, Jan 26..."
3,95321.0,80191.0,2011-01-25,0 days 15:00:00,3600.0,"Good day, ladies and gentlemen, and welcome to...",49346,8453,18671.0,Albemarle Corporation,"Albemarle Corp., Q4 2010 Earnings Call, Jan 25..."
4,210122.0,80191.0,2012-01-24,0 days 13:00:00,3967.0,"Good day, ladies and gentlemen, and welcome to...",53861,9179,18671.0,Albemarle Corporation,"Albemarle Corp., Q4 2011 Earnings Call, Jan 24..."

In [27]:
df3 = df3[[df3['mostimportantdateutc'] >= '2018-01-01']]
df3.head()

KeyError: "None of [Index([(False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, False, False, False, False, False, False, False, False, False, True, True, True, True, True, False, ...)], dtype='object')] are in the [columns]"